### ISSUE TITLE
useResize

### ISSUE THREAD

**Issue by felixknox** [use-hooks/homepage#1]
A `useResize` hook, that allows components to hook into a window resize event and use the various dimension values. [Sandbox](https://codesandbox.io/s/q96r4xj3j)

Passion 👉🏻 🎉🔥🎉🔥🎉🔥🎉🔥🎉🔥

**Comment by int64ago** [comment]
Looks awesome! you've been added in the organization.

Follow the [create-react-hooks](https://github.com/use-hooks/create-react-hooks) to initializing the project.

Tell me your npm id, i'll then add you.

**Comment by felixknox** [comment]
Super @int64ago https://www.npmjs.com/~felixnielsen cheers and have a merry!

**Comment by int64ago** [comment]
Hi, what's your plan for `useResize`?

**Comment by felixknox** [comment]
@int64ago holidays, will be back in front of the computer on the other side of new years.

**Comment by int64ago** [comment]
:-) feel free to do this, happy holidays!

**Comment by int64ago** [comment]
Close for timeout
